name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main  # Or whichever branch you are using

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build the package (skip tests for faster builds)
      - name: Build the package (no tests)
        run: mvn --batch-mode -DskipTests package

      # Step 4: Run unit tests
      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      # Step 5: Report test results (if needed)
      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      # Step 6: Publish the image to GitHub Container Registry
      - name: Publish the image to GitHub Container Registry (GHCR)
        run: |
          docker login --username jahnavi-vemuri --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
          docker build -t ghcr.io/jahnavi-vemuri/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/jahnavi-vemuri/arithmetic-service:latest

      # Step 7: Publish the image to Azure Container Registry (ACR)
      - name: Publish the image to Azure Container Registry (ACR)
        run: |
          docker login --username practi7 --password ${{ secrets.AZURE_CONTAINER_REGISTRY }} practi7.azurecr.io
          docker tag ghcr.io/jahnavi-vemuri/arithmetic-service:latest practi7.azurecr.io/arithmetic-service:latest
          docker push practi7.azurecr.io/arithmetic-service:latest
