name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2



      - name: Set up JDK 17

        uses: actions/setup-java@v2

        with:

          java-version: '17'

          distribution: 'adopt'



      - name: Build the package (no tests)

        run: mvn --batch-mode -DskipTests package



      - name: Run the unit tests

        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test



      - name: Report test results

        if: always()

        uses: dorny/test-reporter@v1

        with:

          name: Maven Tests

          path: target/surefire-reports/*.xml

          reporter: java-junit

          fail-on-error: true

      - name: Publish the image to github container registry
        run: |
          docker login --username jvemuri --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
          docker build -t ghcr.io/jvemuri/arithmetic-service:1 --file Dockerfile .
          docker push ghcr.io/jvemuri/arithmetic-service:1

      - name: Publish the image to azure container registry
        run: |
          docker login --username practi7 --password ${{ secrets.AZURE_CONTAINER_REGISTRY }} practi7.azurecr.io
          docker tag ghcr.io/jvemuri/arithmetic-service:1 practi7.azurecr.io/arithmetic-service:1
          docker push practi7.azurecr.io/arithmetic-service:1
